appName: ${{values.name}}

serviceName:  ${{values.name}}

namespace:  ${{values.name}}

hostName: ${{values.repoHost}}

giteaBaseUrl: https://${{values.repoHost}}:8443/gitea/giteaAdmin

imageBase: ${{values.repoHost}}:8443/gitea/giteaadmin

replicaCount: 4

envName: dev

image:
  registry: ${{values.repoHost}}:8443/gitea/giteaadmin
  tag: placeholder


service:
  type: ClusterIP
  port: 8080

ingress:
  enable: true
  host: ${{values.repoHost}}