apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: Creates An App with CI and CD Workflows
  name: app-with-ci-cd
  title: Deploy an Application with CICD configured
  tags:
    - go
spec:
  owner: user:guest
  type: service
  parameters:
    - title: Service Info
      required:
        - serviceName
      properties:
        serviceName:
          title: Service Name
          type: string
          default: riv2024demo
          pattern: ^[a-z\d]{1,64}$
          description: Provide service name
        # costCenter:
        #   type: string
        #   title: Cost Center
        #   default: C0001
        #   description: Provide CostCenter ID for finance management
        # language:
        #   title: Language
        #   type: string
        #   default: go
        #   enum:
        #     - go
        # readOnlyGroup:
        #   type: string
        #   title: Access Group Name (ReadOnly)
        #   default: cnoe-ro-ad@cnoe.io
        #   description: AD Group Name to provide read only access
        # readWriteGroup:
        #   type: string
        #   title: Access Group Name (ReadWrite)
        #   default: cnoe-rw-ad@cnoe.io
        #   description: AD Group Name to provide read & write only access

    - title: Source Control Configuration
      required:
        - repoHost
      properties:
        repoHost:
          title: Repository Host
          type: string
          default: cnoe.localtest.me
          enum:
            - cnoe.localtest.me
        owner:
          type: string
          title: Owner
          default: cnoe.io
          description: Repo Owner Name
        isNewAppRepo:
          title: Would you like us to create the application repository for you?
          type: string
          default: Yes
          enum:
            - Yes
        isNewDeployRepo:
          title: Would you like us to create the deploy repository for you?
          type: string
          default: Yes
          enum:
            - Yes  
        
  steps:
    - id: deploy-template
      name: Generating application deployment template
      action: fetch:template
      input:
        url: ./infra
        targetPath: ./app-deploy
        values:
          name: ${{parameters.serviceName}}
          repoHost: ${{parameters.repoHost}}
    
    - id: app-template
      name: Generating application code template
      action: fetch:template
      input:
        url: ./application
        targetPath: ./app
        values:
          name: ${{parameters.serviceName}}
          repoHost: ${{parameters.repoHost}}

    - id: publish-deploy-repo
      name: Publishing to a gitea deploy git repository
      action: publish:gitea
      input:
        description: This is an example app
        sourcePath: ./app-deploy
        repoUrl: ${{parameters.repoHost}}:8443/gitea?repo=${{parameters.serviceName}}-deploy
        defaultBranch: main
    
    - id: publish-app-repo
      name: Publishing to a gitea application git repository
      action: publish:gitea
      input:
        description: This is an example app
        sourcePath: ./app
        repoUrl: ${{parameters.repoHost}}:8443/gitea?repo=${{parameters.serviceName}}
        defaultBranch: main

    - id: create-applicationset-for-app
      name: Create ArgoCD ApplicationSet for Application
      action: cnoe:kubernetes:apply
      input:
        namespaced: true
        manifestPath: ./app-deploy/app/app-set.yaml
        clusterName: local

    - id: create-application-for-app-infra
      name: Create ArgoCD Application for Application CI CD
      action: cnoe:kubernetes:apply
      input:
        namespaced: true
        manifestPath: ./app-deploy/ci-cd/app.yaml
        clusterName: local

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-app-repo'].output.repoContentsUrl }}
        catalogInfoPath: 'catalog-info.yaml'

  output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
