apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.name}}-ci-cd
  namespace: argocd
  labels:
    entity-id: ${{values.name}}
spec:
  project: default
  source:
    path: ci-cd/chart
    repoURL: https://${{values.repoHost}}:8443/gitea/giteaadmin/${{values.name}}-deploy
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.name}}-ci-cd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
---