apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: idpbuilder-cacert
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
          namespace: default
      remoteNamespace: default
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          namespace: default
          type: ConfigMap
        url: kubernetes.default