# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: eso-store
#   namespace: default
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: eso-store
#   namespace: default
# rules:
# - apiGroups:
#   - ""
#   resources:
#   - secrets
#   verbs:
#   - get
#   - list
#   - watch
# - apiGroups:
#   - authorization.k8s.io
#   resources:
#   - selfsubjectrulesreviews
#   verbs:
#   - create
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: eso-store
#   namespace: default
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: eso-store
# subjects:
# - kind: ServiceAccount
#   name: eso-store
#   namespace: default
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: idpbuilder-cacert
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
          namespace: default
      remoteNamespace: default
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          namespace: default
          type: ConfigMap
        url: kubernetes.default