apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: "{{ .Values.serviceName }}-deploy-template"
  namespace: {{ .Values.namespace }}
spec:
  serviceAccountName: admin
  arguments:
    parameters:
      - name: deployrepo
        value: "{{ .Values.giteaBaseUrl }}/{{ .Values.serviceName}}-deploy"
      - name: image-tag
        value: "0.0.1"
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 256Mi
  templates:
    - name: deploy-workflow
      dag:
        tasks:
          - name: "{{ .Values.serviceName }}-deployment-workflow"
            template: deployment-workflow
            arguments:
              parameters:
                - name: deployrepo
                  value: "{{`{{workflow.parameters.deployrepo}}`}}"
                - name: image-tag
                  value: "{{`{{workflow.parameters.image-tag}}`}}"
    - name: deployment-workflow
      inputs:
        parameters:
          - name: deployrepo
          - name: image-tag
      dag:
        tasks:
          - name: clone-deploy-repo
            template: clonerepo
            arguments:
              parameters:
                - name: deployrepo
                  value: "https://{{`{{inputs.parameters.deployrepo}}`}}"
                - name: branch
                  value: "main"
          - name: update-image-version
            template: update-manifest
            arguments:
              parameters:
                - name: deployrepo
                  value: "{{`{{inputs.parameters.deployrepo}}`}}"
                - name: tag-version
                  value: "{{`{{inputs.parameters.image-tag}}`}}"
            depends: "clone-deploy-repo"
    - name: clonerepo
      inputs:
        parameters:
          - name: deployrepo
          - name: branch
          - name: envname
      container:
        volumeMounts:
          - mountPath: /workdir
            name: workdir
        image: alpine/git:v2.45.1
        workingDir: /workdir
        args:
          - clone
          - --depth
          - "1"
          - --branch
          - "{{`{{inputs.parameters.branch}}`}}"
          - --single-branch
          - "{{`{{inputs.parameters.deployrepo}}`}}"
          - -c
          - http.sslVerify=false
          - .
    - name: update-manifest
      inputs:
        parameters:
          - name: deployrepo
          - name: tag-version
      container:
        volumeMounts:
          - mountPath: /workdir
            name: workdir
        image: alpine/git:v2.45.1
        envFrom:
          - secretRef:
              name: gitea-credentials
        workingDir: /workdir
        command: ["/bin/sh"]
        args:
          - -c
          - >-  
            set -x &&
            git clone https://{{`{{inputs.parameters.deployrepo}}`}}.git -c http.sslVerify=false &&
            repo={{`{{inputs.parameters.deployrepo}}`}} &&
            repo_name=`echo -n $repo | awk -F/ '{print $NF}'` &&
            image_version={{`{{inputs.parameters.tag-version}}`}} &&
            sed -i "s/  tag: .*/  tag: $image_version/g" values.yaml &&
            cat values.yaml &&
            git status &&
            m_count=$(git status -s | wc -l) &&
            if [ $m_count == 1 ]; then
              git config --global user.email "noreply@aws.com" 
              git config --global user.name ARGO
              git remote set-url origin https://$GITEA_USERNAME:$GITEA_TOKEN@{{`{{inputs.parameters.deployrepo}}`}}.git
              git add values.yaml
              git commit -m "Updated image version to $image_version"
              git push --set-upstream origin main
            else
              echo "No updates to values file, skipping git push"
              echo -n "skip_cd" > /workdir/cd_argo_flag.txt
            fi
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: "{{ .Values.serviceName }}-deploy-webhook"
  namespace: {{ .Values.namespace }}
spec:
  event:
    selector: "payload.app-name != '' && payload.app-name == ['{{ .Values.serviceName }}']"
  submit:
    workflowTemplateRef:
      name: "{{ .Values.serviceName }}-deploy-template"
    arguments:
      parameters:
      - name: image-tag
        valueFrom:
          event: "payload.image_tag"