apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: "{{ .Values.serviceName }}-deploy-template"
  namespace: {{ .Values.namespace }}
spec:
  serviceAccountName: admin
  entrypoint: deploy-workflow
  arguments:
    parameters:
      - name: deployrepo
        value: "{{ .Values.giteaBaseUrl }}/{{ .Values.serviceName}}-deploy"
      - name: image-tag
        value: "0.0.1"
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 256Mi
  templates:
    - name: deploy-workflow
      dag:
        tasks:
          - name: "{{ .Values.serviceName }}-deployment-workflow"
            template: deployment-workflow
            arguments:
              parameters:
                - name: deployrepo
                  value: "{{`{{workflow.parameters.deployrepo}}`}}"
                - name: image-tag
                  value: "{{`{{workflow.parameters.image-tag}}`}}"
    - name: deployment-workflow
      inputs:
        parameters:
          - name: deployrepo
          - name: image-tag
      dag:
        tasks:
          - name: clone-deploy-repo
            template: clonerepo
            arguments:
              parameters:
                - name: deployrepo
                  value: "{{`{{inputs.parameters.deployrepo}}`}}"
                - name: branch
                  value: "main"
          - name: update-image-version
            template: update-manifest
            arguments:
              parameters:
                - name: deployrepo
                  value: "{{`{{inputs.parameters.deployrepo}}`}}"
                - name: tag-version
                  value: "{{`{{inputs.parameters.image-tag}}`}}"
            depends: "clone-deploy-repo"
    - name: clonerepo
      inputs:
        parameters:
          - name: deployrepo
          - name: branch
      container:
        volumeMounts:
          - mountPath: /workdir
            name: workdir
        image: alpine/git:v2.45.1
        workingDir: /workdir
        args:
          - clone
          - --depth
          - "1"
          - --branch
          - "{{`{{inputs.parameters.branch}}`}}"
          - --single-branch
          - "{{`{{inputs.parameters.deployrepo}}`}}"
          - -c
          - http.sslVerify=false
          - .
    - name: update-manifest
      inputs:
        parameters:
          - name: deployrepo
          - name: tag-version
      container:
        volumeMounts:
          - mountPath: /workdir
            name: workdir
        image: alpine/git:v2.45.1
        envFrom:
          - secretRef:
              name: gitea-credentials
        workingDir: /workdir
        command: ["/bin/sh"]
        args:
          - -c
          - >-  
            set -x;
            repo={{`{{inputs.parameters.deployrepo}}`}};
            repo_name=`echo -n $repo | awk -F/ '{print $NF}'`;
            repo_base=`echo -n $repo | cut -d'/' -f3-`;
            image_version={{`{{inputs.parameters.tag-version}}`}};
            sed -i "s/  tag: .*/  tag: $image_version/g" app/chart/values.yaml;
            cat app/chart/values.yaml;
            git status;
            m_count=$(git status -s | wc -l);
            if [ $m_count == 1 ]; then
              git config --global user.email "noreply@aws.com";
              git config --global user.name ARGO;
              git remote set-url origin https://$GITEA_USERNAME:$GITEA_TOKEN@$repo_base.git;
              git add app/chart/values.yaml;
              git commit -m "Updated image version to $image_version";
              git push --set-upstream origin main;
            else
              echo "No updates to values file, skipping git push";
            fi
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: "{{ .Values.serviceName }}-deploy-webhook"
  namespace: {{ .Values.namespace }}
spec:
  event:
    selector: '"app_name" in payload and payload.app_name != "" and payload.app_name == "{{ .Values.serviceName }}"'
  submit:
    workflowTemplateRef:
      name: "{{ .Values.serviceName }}-deploy-template"
    arguments:
      parameters:
      - name: image-tag
        valueFrom:
          event: "payload.image_tag"