apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: "{{ .Values.serviceName }}-ci-template"
  namespace: {{ .Values.namespace }}
  labels:
    entity-id: "{{ .Values.serviceName }}"
spec:
  workflowMetadata:
    labels:
      entity-id: "{{ .Values.serviceName }}"
  serviceAccountName: admin
  entrypoint: ci-build
  arguments:
    parameters:
      - name: apprepo
        value: "{{ .Values.giteaBaseUrl }}/{{ .Values.serviceName }}"
      - name: branch
        value: main
      # - name: deployrepo
      #   value: "{{ .Values.giteaBaseUrl }}/{{ .Values.serviceName }}-deploy"
      - name: image
        value: "{{ .Values.image.registry }}"
      - name: tag-version
        value: "0.0.1"
      - name: workflow-event-url
        value: "{{ .Values.hostName }}:8443/argo-workflows/api/v1/events/{{ .Values.namespace }}/"
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 256Mi
  templates:
    - name: ci-build
      dag:
        tasks:
          - name: clone
            template: clonerepo
            arguments:
              parameters:
                - name: apprepo
                  value: "{{`{{workflow.parameters.apprepo}}`}}"
                - name: branch
                  value: "{{`{{workflow.parameters.branch}}`}}"
          - name: build-and-test
            template: go-build
            depends: "clone"
          - name: generate-new-tag-version
            template: create-new-tag
            depends: "build-and-test"
          - name: docker-build-and-push-image
            template: build-image-kaniko
            arguments:
              parameters:
                - name: image
                  value: "{{`{{workflow.parameters.image}}`}}"
                - name: tag-version
                  value: "{{`{{tasks.generate-new-tag-version.outputs.parameters.tag-version}}`}}"
            depends: "generate-new-tag-version"
          - name: push-new-tag-version
            template: push-tag
            arguments:
              parameters:
                - name: apprepo
                  value: "{{`{{workflow.parameters.apprepo}}`}}"
            depends: "docker-build-and-push-image"
          - name: invoke-cd-workflow
            template: invoke-cd-workflow
            arguments:
              parameters:
                - name: workflow-event-url
                  value: "{{`{{workflow.parameters.workflow-event-url}}`}}"
                - name: image-tag
                  value: "{{`{{tasks.generate-new-tag-version.outputs.parameters.tag-version}}`}}"
                - name: app-name
                  value: "{{ .Values.serviceName }}"
            depends: "docker-build-and-push-image"

    - name: clonerepo
      inputs:
        parameters:
          - name: apprepo
          - name: branch
      container:
        volumeMounts:
          - mountPath: /workdir
            name: workdir
        image: alpine/git:v2.45.1
        workingDir: /workdir
        args:
          - clone
          - --depth
          - "1"
          - --branch
          - "{{`{{inputs.parameters.branch}}`}}"
          - --single-branch
          - "{{`{{inputs.parameters.apprepo}}`}}"
          - -c
          - http.sslVerify=false
          - .

    - name: go-build
      container:
        image: golang:1.22
        volumeMounts:
          - mountPath: /workdir
            name: workdir
        workingDir: /workdir
        command:
          - go
        args:
          - build
          - -v
          - -o
          - myapp

    - name: create-new-tag
      container:
        image: alpine:3.20
        volumeMounts:
          - mountPath: /workdir
            name: workdir
        workingDir: /workdir
        command: ["/bin/sh"]
        args:
          - -c
          - >-
            set -x;
            CURRENT_VERSION=$(cat version.txt);
            MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1);
            MINOR=$(echo $CURRENT_VERSION | cut -d. -f2);
            PATCH=$(echo $CURRENT_VERSION | cut -d. -f3);
            NEW_PATCH=$((PATCH + 1));
            NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}";
            echo "Current version: $CURRENT_VERSION";
            echo "New version: $NEW_VERSION";
            echo -n "$NEW_VERSION" > version.txt
      outputs:
        parameters:
          - name: tag-version
            valueFrom:
              path: /workdir/version.txt
    
    - name: build-image-kaniko
      inputs:
        parameters:
          - name: image
          - name: tag-version
      volumes:
        - name: docker-config
          configMap:
            name: docker-config
      container:
        image: gcr.io/kaniko-project/executor:latest
        volumeMounts:
          - name: workdir
            mountPath: /workdir
          - name: docker-config
            mountPath: /kaniko/.docker
        workingDir: /workdir
        resources:
          limits:
            cpu: 1
            memory: 2Gi
        env:
          - name: DOCKER_CONFIG
            value: /kaniko/.docker
        args:
          - --dockerfile=Dockerfile
          - --context=.
          - --destination={{`{{inputs.parameters.image}}`}}:{{`{{inputs.parameters.tag-version}}`}}
          - --skip-tls-verify
          - --cache=false

    - name: push-tag
      inputs:
        parameters:
          - name: apprepo
      container:
        volumeMounts:
          - mountPath: /workdir
            name: workdir
        image: alpine/git:v2.45.1
        envFrom:
          - secretRef:
              name: gitea-credentials
        workingDir: /workdir
        command: ["/bin/sh"]
        args:
          - -c
          - >-  
            set -x;
            repo={{`{{inputs.parameters.apprepo}}`}};
            repo_name=`echo -n $repo | awk -F/ '{print $NF}'`;
            repo_base=`echo -n $repo | cut -d'/' -f3-`;
            cat version.txt;
            git status;
            m_count=$(git status -s | grep version | wc -l);
            if [ $m_count == 1 ]; then
              git config --global user.email "noreply@aws.com";
              git config --global user.name ARGO;
              git remote set-url origin https://$GITEA_USERNAME:$GITEA_TOKEN@$repo_base.git;
              git add version.txt;
              git commit -m "Bump App Version from CI Workflow";
              git push --set-upstream origin main;
            else
              echo "No updates to version file, skipping git push";
            fi

    - name: invoke-cd-workflow
      inputs:
        parameters:
          - name: workflow-event-url
          - name: image-tag
          - name: app-name
      container:
        image: alpine:3.20
        envFrom:
          - secretRef:
              name: gitea-credentials
        env:
          - name: ARGO_TOKEN
            valueFrom:
              secretKeyRef:
                name: argo-token
                key: token
        volumeMounts:
          - mountPath: /workdir
            name: workdir
        workingDir: "/workdir"
        command: ["/bin/sh"]
        args:
          - -c
          - >-
            set -x;
            [ -z "${ARGO_TOKEN:-}" ] && echo "Error: ARGO_TOKEN not set" && exit 1;
            apk add --no-cache curl jq;
            cd_workflow_url="https://{{`{{inputs.parameters.workflow-event-url}}`}}";
            image_tag="{{`{{inputs.parameters.image-tag}}`}}";
            app_name="{{`{{inputs.parameters.app-name}}`}}";
            for i in $(seq 1 3); do
                if curl -k -sf \
                    -X POST \
                    -H "Content-Type: application/json" \
                    -H "Authorization: Bearer ${ARGO_TOKEN}" \
                    -d "{\"image_tag\":\"${image_tag}\", \"app_name\":\"${app_name}\"}" \
                    "${cd_workflow_url}"; then
                    echo "CD workflow invoked successfully";
                    exit 0;
                fi;
                [ $i -eq 3 ] && echo "All retries failed" && exit 1;
                echo "Attempt $i failed. Retrying..." && sleep 5;
            done
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: "{{ .Values.serviceName }}-ci-webhook"
  namespace: {{ .Values.namespace }}
spec:
  event:
    selector: metadata["x-gitea-event"] == ["push"] and none(payload.commits, .author.name == "ARGO")
  submit:
    workflowTemplateRef:
      name: "{{ .Values.serviceName }}-ci-template"
    arguments:
      parameters:
      - name: image-tag
        valueFrom:
          event: "payload.image_version"