apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: "{{ .Values.serviceName }}"
  namespace: "{{ .Values.namespace }}"
spec:
  promotionPolicies:
  - stage: dev
    autoPromotionEnabled: true
  - stage: stage
    autoPromotionEnabled: true
  - stage: prod
    autoPromotionEnabled: false
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: "{{ .Values.serviceName }}"
  namespace: "{{ .Values.serviceName }}"
spec:
  subscriptions:
  - image:
      repoURL: advaitt.people.aws.dev:8443/gitea/giteaadmin/{{ .Values.serviceName }} # Watch for new versions of this image
      # semverConstraint: ^0.0.0 # Only watch for versions that match this constraint
---
{{- $stageVar := print "${{ '${{' }} ctx.stage ${{ '}}' }}" -}}
{{- $gitRepoVar := print "${{ '${{' }} vars.gitRepo ${{ '}}' }}" -}}
{{- $imageTagVar := print "${{ '${{' }} imageFrom(vars.imageRepo).Tag ${{ '}}' }}" -}}
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promo-process
  namespace: "{{ .Values.serviceName }}"
spec:
  vars:
  - name: gitRepo
    value: https://advaitt.people.aws.dev:8443/gitea/giteaadmin/{{ .Values.serviceName }}-deploy
  - name: imageRepo
    value: advaitt.people.aws.dev:8443/gitea/giteaadmin/{{ .Values.serviceName }}
  steps:
  - uses: argocd-update
    config:
      apps:
      - name: "{{ .Values.serviceName }}-{{ $stageVar }}"
        sources:
        - repoURL: {{ $gitRepoVar }}
          helm:
            images:
            - key: image.tag
              value: {{ $imageTagVar }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: "{{ .Values.serviceName }}"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: "{{ .Values.serviceName }}"
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promo-process
  verification:
    analysisTemplates:
    - name: "{{ .Values.serviceName }}"
      kind: ClusterAnalysisTemplate
    args:
    - name: baseURL
      value: "https://{{ .Values.hostName }}:8443"
    - name: subPath
      value: "/{{ .Values.serviceName }}/dev"
    - name: field
      value: env
    - name: value
      value: dev
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage
  namespace: "{{ .Values.serviceName }}"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: "{{ .Values.serviceName }}"
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promo-process
  verification:
    analysisTemplates:
    - name: "{{ .Values.serviceName }}"
      kind: ClusterAnalysisTemplate
    args:
    - name: baseURL
      value: "https://{{ .Values.hostName }}:8443"
    - name: subPath
      value: "/{{ .Values.serviceName }}/stage"
    - name: field
      value: env
    - name: value
      value: stage
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: "{{ .Values.serviceName }}"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: "{{ .Values.serviceName }}"
    sources:
      stages:
      - stage
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promo-process
  verification:
    analysisTemplates:
    - name: "{{ .Values.serviceName }}"
      kind: ClusterAnalysisTemplate
    args:
    - name: baseURL
      value: "https://{{ .Values.hostName }}:8443"
    - name: subPath
      value: "/{{ .Values.serviceName }}/stage"
    - name: field
      value: env
    - name: value
      value: prod