apiVersion: batch/v1
kind: Job
metadata:
  name: ci-cd-webhook-provisioner
  namespace: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: admin
      containers:
        - name: bash
          envFrom:
            - secretRef:
                name: gitea-credentials
          env:
            - name: ARGO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argo-token
                  key: token
            - name: HOOKS_API_URL
              value: "https://{{ .Values.hostName }}:8443/gitea/api/v1/repos/giteaAdmin/{{ .Values.appName }}/hooks"
            - name: WEBHOOK_URL
              value: "https://{{ .Values.hostName }}:8443/argo-workflows/api/v1/events/{{ .Values.namespace }}/"
          image: alpine/k8s:1.31.0
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              set -eu;
              for var in GITEA_USERNAME GITEA_PASSWORD HOOKS_API_URL GITEA_TOKEN ARGO_TOKEN WEBHOOK_URL; do
                [ -z "$(eval echo \$$var)" ] && echo "Error: $var not set" && exit 1;
              done;
              apk add --no-cache curl yq jq;
              gitea_auth=$(echo -n "${GITEA_USERNAME}:${GITEA_PASSWORD}" | base64);
              cat > docker_config.yaml << EOF
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: docker-config
                namespace: {{ .Values.namespace }}
              data:
                config.json: |
                  {"auths":{"{{ .Values.giteaBaseUrl }}":{"auth":"${gitea_auth}"}}}
              EOF
              ;
              kubectl apply -f docker_config.yaml || exit 1;
              for i in $(seq 1 3); do
                if curl -k -X POST "${HOOKS_API_URL}" \
                  -H "accept: application/json" \
                  -H "Authorization: token ${GITEA_TOKEN}" \
                  -H "Content-Type: application/json" \
                  -d "{\"branch_filter\":\"main\",\"type\":\"gitea\",\"events\":[\"push\"],\"authorization_header\":\"Bearer ${ARGO_TOKEN}\",\"config\":{\"url\":\"${WEBHOOK_URL}\",\"content_type\":\"json\"},\"active\":true}" \
                  -fsS; then
                  echo "Webhook created successfully";
                  exit 0;
                fi;
                [ $i -eq 3 ] && echo "All retries failed" && exit 1;
                echo "Attempt $i failed. Retrying..." && sleep 5;
              done
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-credentials
  namespace: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  secretStoreRef:
    name: gitea
    kind: ClusterSecretStore
  refreshInterval: "0"
  target:
    name: gitea-credentials
  data:
    - secretKey: GITEA_USERNAME
      remoteRef:
        key: gitea-credential
        property: username
    - secretKey: GITEA_PASSWORD
      remoteRef:
        key: gitea-credential
        property: password
    - secretKey: GITEA_TOKEN
      remoteRef:
        key: gitea-credential
        property: token
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-token
  namespace: "{{ .Values.namespace }}"
  annotations:
    kubernetes.io/service-account.name: admin
    argocd.argoproj.io/sync-wave: '-10'
type: kubernetes.io/service-account-token